apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wxkf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wxkf
    app.kubernetes.io/part-of: ci10t-786-0009-app
  name: devfile-sample-wxkf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wxkf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wxkf
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0009-tenant/ci10t-786-0009-app/devfile-sample-wxkf@sha256:06776319ed8974521e9334ab211f9227c1e7856ff20e7a554aad2a476cc7adb8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
